### ISSUE TITLE
Library situation

### ISSUE THREAD

**Issue by dschuermann** [SufficientlySecure/ics-import-export#19]
a) Instead of having "android-support-v4.jar" inside the libs folder, we should use the one provided by the Android SDK using a proper dependency definition with a version code.

b) I am not sure how to handle the other libs correctly. I think it's good enough for now to include the precompiled jars, but it would be much nicer to rely on libs from JCenter or including them with git submodules. At least we should document how they were build inside the README (I saw your specific instructions in https://github.com/dschuermann/ical-import-export/commit/f50ec5724d6722f0824d59150831a08a9b33547d and https://github.com/dschuermann/ical-import-export/commit/3e36642a15c5195f3372e93d9ca3677a75591a58 )

@jgriffiths

**Comment by dschuermann** [comment]
BTW: https://github.com/ical4j/ical4j/wiki/Android

**Comment by jgriffiths** [comment]
Thanks for the link, local libs are now replaced.
