### ISSUE TITLE
Import replaced same events from other calender

### ISSUE THREAD

**Issue by dschuermann** [SufficientlySecure/ics-import-export#23]
Duplicates should only be replaced when they are in the same calender

**Comment by jgriffiths** [comment]
This is the intended behaviour given the presence of a UID, assuming the 'Keep UIDs' setting is enabled. UIDs are intended to ensure the events are uniquely represented.

I agree that this may be counter-intuitive or undesirable given how some people use multiple calendars currently. I will add an option to make UUIDs unique globally and default it to off.
